// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmOCAIY1odCYOda2m69lZpHr2mdXIgpVk',
    appId: '1:342882623214:web:7e827d596e38788e905dff',
    messagingSenderId: '342882623214',
    projectId: 'sangambyfc',
    authDomain: 'sangambyfc.firebaseapp.com',
    storageBucket: 'sangambyfc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0f4qgC6ih4ZlgY8mmgzhULljzRJeMN-I',
    appId: '1:342882623214:android:b6cafa127ee25d48905dff',
    messagingSenderId: '342882623214',
    projectId: 'sangambyfc',
    storageBucket: 'sangambyfc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT9wxJzRUBI1oQrxl81ldppdvW7wpQWVI',
    appId: '1:342882623214:ios:daf604f2eb335c82905dff',
    messagingSenderId: '342882623214',
    projectId: 'sangambyfc',
    storageBucket: 'sangambyfc.firebasestorage.app',
    iosBundleId: 'com.namkeen.factory.namkeenManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT9wxJzRUBI1oQrxl81ldppdvW7wpQWVI',
    appId: '1:342882623214:ios:daf604f2eb335c82905dff',
    messagingSenderId: '342882623214',
    projectId: 'sangambyfc',
    storageBucket: 'sangambyfc.firebasestorage.app',
    iosBundleId: 'com.namkeen.factory.namkeenManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmOCAIY1odCYOda2m69lZpHr2mdXIgpVk',
    appId: '1:342882623214:web:a7272889bab0422b905dff',
    messagingSenderId: '342882623214',
    projectId: 'sangambyfc',
    authDomain: 'sangambyfc.firebaseapp.com',
    storageBucket: 'sangambyfc.firebasestorage.app',
  );
}
